### ISSUE TITLE
Add the ability to like/unlike an activity within an app

### ISSUE THREAD

**Issue by lmb244** [lmco/eurekastreams#141]
the ability to like/unlike will be a feature added in release 1.0.   As an enhancement to that feature, consider adding the ability to like/unlike within a stream app on the start page.

**Comment by kwalkerm** [comment]
I believe that adding the like/unlike feature will help with the usability issues associated with having just a save button. Having just the save button is a bit ambiguous, but once there is a like button too, by process of elimination, people will realize that it's more of a bookmark.  We still need to deal with conveying to the user the concept of content expiration... I believe a tool tip on the save button can go a long way.

**Comment by lmb244** [comment]
Being developed for 1.0
