### ISSUE TITLE
B-06098 Allow users to get notifications for Groups they are a member of

### ISSUE THREAD

**Issue by lmb244** [lmco/eurekastreams#159]
Users are joining groups and would like to be notified when an activity has been posted in a specific group.   According to the community manager a number of employees are requesting this feature.

I think there are a couple of different paths that can be taken here.   
1.  When a user joins a group, he/she will automatically receive a notification in the system and via email that an activity has been posted.   He/she will then have the ability to cherry pick the groups that he/she wants to receive notification from via the notifications tab.  When the user leaves the group, the group will automatically be removed from the notifications tab and emails/notifications for that group will be disabled. 

Alternative:  All or nothing for the notifications:  They get an email/notification for every group that he/she has joined.  They have the option to turn it off.

**Comment by keaner** [comment]
In terms of time the all or nothing option could safely be completed in about a week by one person, whereas the more complex version would probably be about a whole iteration.

**Comment by jajoseph** [comment]
Updated designs are posted on eurekastreams.org here: http://www.eurekastreams.org/docs/product-specification/future-releases/r1-0-manage-and-receive-notifications/

**Comment by lmb244** [comment]
worked, tested and will be deployed with .9.2
