### ISSUE TITLE
No horizontal Scrool Bar appears when Eureka is resized

### ISSUE THREAD

**Issue by lmb244** [lmco/eurekastreams#194]
No horizontal scrolling bar appears after resizing Internet Explorer 7's window to a width less than the width of the Eureka Streams display. - Happens in FF to

**Comment by kwalkerm** [comment]
One user reported it occurring in FF too...  I removed all toolbars and I got H scrolling. Then I restart firefox with the org set of toolbar configuration and the H scrolling is still there. may have been a fluke on my end.

**Comment by lmb244** [comment]
fixed and tested.  will be deployed with 1.0
