### ISSUE TITLE
First Time users are not being automatically directed to the TOS modal when accessing the system via the following email

### ISSUE THREAD

**Issue by lmb244** [lmco/eurekastreams#70]
This is a high priority defect because it is a usability issue that everyone new to the system will see.    When the user is accessing Eureka from a following email, the TOS modal is not being displayed.

**Comment by wblakecaldwell** [comment]
Working on this now.

**Comment by lmb244** [comment]
Perfect. Thanks

**Comment by wblakecaldwell** [comment]
Checked in the fix.  All I have left is to cache the system settings.

**Comment by lmb244** [comment]
This item has passed testing.   It will be deployed with .9.1
