### ISSUE TITLE
Back button and forward button is not enabled

### ISSUE THREAD

**Issue by lmb244** [lmco/eurekastreams#75]
The back and forward button does not work within Eureka Streams, please enable

**Comment by wblakecaldwell** [comment]
It's not that they don't work all together, it's that on pages with tabs, the page redirects you to itself with the first tab selected.  We should just update the tab control to open to the first tab when not told in the URL which to show.

**Comment by lmb244** [comment]
This has passed testing and will be closed.   It will be deployed with the .9.1 release to production.   There was one part of this request that will need to be revisited at a later date and that is the functionality associated with the back button on the start page.   The start page had more complex code related to the app that affected the back button functionality from being implemented quickly.   The decision was made to implement the back button functionality everyone else and then revisit this area.
