### ISSUE TITLE
Organization Coordinators should be able to manage categories

### ISSUE THREAD

**Issue by lmb244** [lmco/eurekastreams#90]
Organization Coordinators need to have a way to easily manage the categories associated with gadgets.  This request is really going to have to be planned out; because ideas such as the following will have to be taken into consideration:  If one organization coordinator deletes a category will it have a ripple effect through the other organizations or will categories be specific to an organization, if so what type of code will have to be written to make sure that others can't access gadgets from other organizations.

**Comment by jajoseph** [comment]
Closing Request 59 as a duplicate of this request.  Here is more information from Request 59: Provide Organization Coordinators with the ability to create, edit and delete the categories associated with gadgets and themes. This would also have to address, how it would span across organizations.

**Comment by lmb244** [comment]
closing
